name: Build Blockstream Green Android App
runs-on: self-hosted

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK and Android SDK Tools
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Install Android SDK Tools
      run: |
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-7302050_latest.zip -O android-sdk-tools.zip
        unzip -qq android-sdk-tools.zip -d $HOME/android-sdk
        echo "export ANDROID_SDK_ROOT=$HOME/android-sdk" >> $GITHUB_ENV
        echo "export PATH=$HOME/android-sdk/cmdline-tools/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV
        sdkmanager "build-tools;33.0.1" "platform-tools" "platforms;android-30" --sdk_root=$HOME/android-sdk

    - name: Clone Blockstream Green Android repository
      run: git clone https://github.com/Blockstream/green_android.git

    - name: Build the Android app
      working-directory: ./green_android
      run: ./gradlew build

    - name: Upload APKs as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: green_android/build/outputs/apk/*/release/*.apk
